### ISSUE TITLE
Your Sensors Sketch

### ISSUE THREAD

**Issue by pieman64** [PaulRB/WemosSensor#1]
Thanks for making your sensors sketch available @PaulRB

Regards
Pieman

**Comment by PaulRB** [comment]
Was that about the voltage divider on the analog input?

**Comment by pieman64** [comment]
Yes and I'm actually a big fan of the h/w.
If the product is to move forward it needs a site where comments can be freely made.
Poor show.

**Comment by PaulRB** [comment]
Not an issue, just a discussion.
