### ISSUE TITLE
Battery directly to sensor?

### ISSUE THREAD

**Issue by Albin76** [PaulRB/WemosSensor#2]
Hi. I absolutely love your setup and I have learned loads from studying your code (and your insights on the Wemos forum) and have made a sensor by your instructions that work fine. 

One thing I do not follow and would like to understand is the connection of the sensor directly to battery. Most sensors for example BMP280 have a max VCC that is lower than the max battery voltage (BMP280 is 3.6V according to datasheets) and a fully charged 10440 is approx 4.15V. Connecting them directly to battery and not through the Wemos 3.3 should be more efficient since no conversion losses but is it safe/functional? 

Can you explain please how you have reasoned?

**Comment by PaulRB** [comment]
I should have explained in more detail. The sensor breakout boards I use all have their own 3.3V regulator on board, such as this one:
http://www.ebay.co.uk/itm/BME280-Digital-Temperature-Humidity-Barometric-Pressure
and this one:
http://www.ebay.co.uk/itm/1pcs-HTU21D-Temperature-Humidity-Sensor-Breakout

**Comment by PaulRB** [comment]
If using a sensor board without its own regulator, you could use the 3.3V pin from the Wemos as you suggested.

Thanks for your feedback and appreciation!

**Comment by Albin76** [comment]
Thanks. That explains a lot. I Will see if I have a regulator on mine and
connect thouse directly and by the 3.3V on the others then.

Curious about one thing. May i ask how many days you manage between charges
on a 10440 (and at what sample rate of course)?

I myself have at best 15 days between charges (4.15 to 3.45V) and have a
reading every 15 minutes and use wifi manager.

sön 9 juli 2017 kl. 12:13 skrev Paul <notifications@github.com>:

**Comment by PaulRB** [comment]
I get around 21 days between charges. Sample rate is 15 mins. The Wemos wakes for around 5 or 6 seconds. It has a fixed ip address on my home network, so does not need to wait for DHCP to allocate an address. The battery voltage drops to around 2.6~2.8V before it stops working.
